* xmonad.hs

Um arquivo básico de configuração do xmonad (/​​home/andrei/.xmonad/xmonad.hs):
#+begin_src haskell
import XMonad
import XMonad.Config.Desktop
import XMonad.Hooks.DynamicLog
import XMonad.Util.SpawnOnce
import XMonad.Layout.Spacing
import XMonad.Util.EZConfig (additionalKeysP)
import XMonad.Util.Run

-- My custom variables --
myBorderWidth = 3
myModMask = mod4Mask -- Sets the super/windows key as modkey
myTerminal = "terminator"

main = xmonad =<< xmobar myConfig

-- myConfig declarado a parte da linha "main" acima para evitar conflito com o "xmobar"
myConfig = def
    { terminal    = myTerminal
    , modMask     = myModMask
    , startupHook = myStartupHook
    , layoutHook  = myLayoutHook
    , borderWidth = myBorderWidth
    } `additionalKeysP` myKeys

myStartupHook = do
    spawnOnce "nitrogen --restore &"
    spawnOnce "pulseaudio --start"
    spawnOnce "compton --config /home/andrei/.config/compton/compton.config"
    spawnOnce "setxkbmap us -variant intl" -- Mechanical US keyboard layout

myLayoutHook = spacingRaw True (Border 0 10 10 10) True (Border 5 5 5 5) True $ layoutHook def

myKeys = 
       -- Volume control using keyboard volume keys
       [ ("<XF86AudioLowerVolume>", spawn "amixer set Master 5%- unmute")
       , ("<XF86AudioRaiseVolume>", spawn "amixer set Master 5%+ unmute")
       , ("M-s", spawn "maim /home/andrei/Pictures/screenshot.png") -- Take screenshot and store it
       ]
#+end_src
* compton.conf

O arquivo de configuração para o compton (\/home\/andrei\/.config\/compton\/compton.conf):
#+begin_src haskell
shadow = true;
detect-rounded-corners = true;
shadow-radius = 5;
shadow-offset-x = 1;
shadow-offset-y = 1;
shadow-opacity = 0.3;
shadow-ignore-shaped = false;
shadow-exclude = [ "name = 'Notification'",
    "override_redirect = 1 && !WM_CLASS@:s",
    "class_g ?= 'Dmenu'",
    "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'",
    "_GTK_FRAME_EXTENTS@:c",
    "class_g ?= 'i3-frame'",
    "class_g ?= 'trayer'"
];
menu-opacity = 1.0;
inactive-opacity = 1.0;
active-opacity = 1;
alpha-step = 0.01;
inactive-dim = 0.0;
blur-background = false;
blur-kern = "3x3box";
fading = false;
fade-delta = 1;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-exclude = [ ];
backend = "xrender";
mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-client-opacity = true;
unredir-if-possible = true;
refresh-rate = 0;
vsync = "none";
dbe = false;
focus-exclude = [ "class_g = 'Cairo-clock'" ];
detect-transient = true;
detect-client-leader = true;
invert-color-include = [ ];
glx-copy-from-front = false;
glx-swap-method = "undefined";
opacity-rule = [ "99:name *?= 'Call'",
	       "90:class_g *?= 'terminator'",
	       "100:name *?= 'Lynx'",
	       "100:name *?= 'toot'",
	       "100:name *?= 'nmon'",
	       "100:name *?= 'httping'",
	       "100:name *?= 'xmobar'",
	       "90:class_g *?= 'emacs'",
	       "100:class_g *?= 'surf' && name *?='suckless.org'",
	       "100:class_g *?= 'tabbed'",
	       "100:name *?= 'newsboat'",
	       "100:class_g = 'XTerm' && !_NET_WM_STATE@:32a",
	       "100:class_g = 'URxvt' && !_NET_WM_STATE@:32a",
	       "0:_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'",
	       "96:_NET_WM_STATE@:32a *= '_NET_WM_STATE_STICKY'"
];
wintypes : {
  tooltip : {
    fade = true;
    shadow = false;
    opacity = 0.85;
    focus = true;
    };  
  fullscreen : {
    fade = true;
    shadow = false;
    opacity = 1;
    focus = true;
    };
};
#+end_src
* .xmobarrc

Arquivo de inicialização do xmobar (\/home\/andrei\/.xmobarrc). O arquivo abaixo foi baseado no template encontrado na wiki.archlinux.org.
Note que o mostrador de volume do áudio depende de um script bash que parseie o comand "amixer" (no arquivo, o script localiza-se em \/home\/andrei\/bin\/volume). 
No campo "run Weather", note que a sigla SBCF é o código ICAO de Belo Horizonte (aeroporto de Confins). Conteúdo:
#+begin_src haskell
Config { 

   -- appearance
     font =         "xft:Bitstream Vera Sans Mono:size=11:bold:antialias=true"
   , bgColor =      "black"
   , fgColor =      "#646464"
   , position =     Top
   , border =       BottomB
   , borderColor =  "#646464"

   -- layout
   , sepChar =  "%"   -- delineator between plugin names and straight text
   , alignSep = "}{"  -- separator between left-right alignment
   , template = "%multicpu% | %coretemp% | %memory% | %dynnetwork% }{ %vol% | %SBCF% | %date% || %kbd% "

   -- general behavior
   , lowerOnStart =     True    -- send to bottom of window stack on start
   , hideOnStart =      False   -- start with window unmapped (hidden)
   , allDesktops =      True    -- show on all desktops
   , overrideRedirect = True    -- set the Override Redirect flag (Xlib)
   , pickBroadest =     False   -- choose widest display (multi-monitor)
   , persistent =       True    -- enable/disable hiding (True = disabled)

   -- plugins
   --   Numbers can be automatically colored according to their value. xmobar
   --   decides color based on a three-tier/two-cutoff system, controlled by
   --   command options:
   --     --Low sets the low cutoff
   --     --High sets the high cutoff
   --
   --     --low sets the color below --Low cutoff
   --     --normal sets the color between --Low and --High cutoffs
   --     --High sets the color above --High cutoff
   --
   --   The --template option controls how the plugin is displayed. Text
   --   color can be set by enclosing in <fc></fc> tags. For more details
   --   see http://projects.haskell.org/xmobar/#system-monitor-plugins.
   , commands = 

        -- weather monitor
        [ Run Weather "SBCF" [ "--template", "<station>: <skyCondition> | <fc=#4682B4><tempC></fc>°C | <fc=#4682B4><rh></fc>%"
                             ] 36000

	-- Volume level (NEED SHELL SCRIPT)
	, Run Com "/home/andrei/bin/volume" [] "vol" 10
        -- network activity monitor (dynamic interface resolution)
        , Run DynNetwork     [ "--template" , "<dev>: <tx>kB/s|<rx>kB/s"
                             , "--Low"      , "1000"       -- units: B/s
                             , "--High"     , "5000"       -- units: B/s
                             , "--low"      , "darkgreen"
                             , "--normal"   , "darkorange"
                             , "--high"     , "darkred"
                             ] 10

        -- cpu activity monitor
        , Run MultiCpu       [ "--template" , "Cpu: <total0>%|<total1>%"
                             , "--Low"      , "50"         -- units: %
                             , "--High"     , "85"         -- units: %
                             , "--low"      , "darkgreen"
                             , "--normal"   , "darkorange"
                             , "--high"     , "darkred"
                             ] 10

        -- cpu core temperature monitor
        , Run CoreTemp       [ "--template" , "Temp: <core0>°C|<core1>°C"
                             , "--Low"      , "70"        -- units: °C
                             , "--High"     , "80"        -- units: °C
                             , "--low"      , "darkgreen"
                             , "--normal"   , "darkorange"
                             , "--high"     , "darkred"
                             ] 50
                          
        -- memory usage monitor
        , Run Memory         [ "--template" ,"Mem: <usedratio>%"
                             , "--Low"      , "20"        -- units: %
                             , "--High"     , "90"        -- units: %
                             , "--low"      , "darkgreen"
                             , "--normal"   , "darkorange"
                             , "--high"     , "darkred"
                             ] 10

        -- time and date indicator 
        --   (%F = y-m-d date, %a = day of week, %T = h:m:s time)
        , Run Date           "<fc=#ABABAB>%F (%a) %T</fc>" "date" 10

        -- keyboard layout indicator
        , Run Kbd            [ ("us(dvorak)" , "<fc=#00008B>DV</fc>")
                             , ("us"         , "<fc=#8B0000>US</fc>")
                             ]
        ]
}
#+end_src
* Aplicações adicionais

Algumas aplicações que são úteis com Xmonad:
xmobar - barra de status;
compton - compositor para transparência de janelas e outros eye candies;
dmenu - execução de aplicações com atalhos do teclado;
pcmanfm - Um file manager leve
pulseaudio - Handler de audio
alsamixer - controle do volume via terminal
nitrogen - Aplicação que cuida do papel de parede (é inicializado pelo xmonad.hs com a flag "--restore" para restaurar o último papel de parede utilizado)
plank - dock de programas;
tint2 - barra de programas abertos;
