#-*- mode: org -*-
#+STARTUP: showall
#+TODO: TODO IN-PROGRESS WAITING DONE

* Org mode reference
  [[https://orgmode.org/worg/org-tutorials/org4beginners.html][Org for beginners]]
  Good source of reference is the info-browser in Emacs. Just use =C-h i=.
  Navigate using <TAB>, n and u keys.

* How to put in source code in the org files
  Shortcut is =C-c C-,= and selecting the "s" option for *source code*.
  #+BEGIN_SRC bash
    ls /home/andreis
    for i in {1..10}; do
        echo "Value of i: $i"
    done
  #+END_SRC

  #+begin_src c
    int main() {
        int i = 0;
        if (i == 0)
            printf("i is equal to 0, duh...\n");
        return 0;
    }
  #+end_src

* Chamada que a namô está nesse momento
  Protocolo Vivo: 20218401061546

* Welcome to Org mode

  Welcome, and thanks for trying out Org mode. Making outlines in
  Org is very simple. It is just text! Just start typing.
  +string through this+
  This is /italic/
  This is in *bold*
  =My code=

** TODO List of TODOs 1
   Trying to get better at org mode

** TODO Developing affinity with org-mode

* This is a headline, it starts with one or more stars
  A heading has one star, a sub-heading two, etc.

** TODO This is a different todo topic
* Working with lists
** Moving around in our outline
** Moving around headlines
